(()=>{
'use strict';
const NS='http://www.w3.org/2000/svg';
const BASE='https://raw.githubusercontent.com/thanglequoc/vietnamese-provinces-database/master/json/geojson';
const STORE='vn-map-editor-v4',OLD_STORE='vn-map-label-config-v2';
const provinces=[['01','ha_noi','Hà Nội'],['04','cao_bang','Cao Bằng'],['08','tuyen_quang','Tuyên Quang'],['11','dien_bien','Điện Biên'],['12','lai_chau','Lai Châu'],['14','son_la','Sơn La'],['15','lao_cai','Lào Cai'],['19','thai_nguyen','Thái Nguyên'],['20','lang_son','Lạng Sơn'],['22','quang_ninh','Quảng Ninh'],['24','bac_ninh','Bắc Ninh'],['25','phu_tho','Phú Thọ'],['31','hai_phong','Hải Phòng'],['33','hung_yen','Hưng Yên'],['37','ninh_binh','Ninh Bình'],['38','thanh_hoa','Thanh Hóa'],['40','nghe_an','Nghệ An'],['42','ha_tinh','Hà Tĩnh'],['44','quang_tri','Quảng Trị'],['46','hue','Huế'],['48','da_nang','Đà Nẵng'],['51','quang_ngai','Quảng Ngãi'],['52','gia_lai','Gia Lai'],['56','khanh_hoa','Khánh Hòa'],['66','dak_lak','Đắk Lắk'],['68','lam_dong','Lâm Đồng'],['75','dong_nai','Đồng Nai'],['79','ho_chi_minh','TP. Hồ Chí Minh'],['80','tay_ninh','Tây Ninh'],['82','dong_thap','Đồng Tháp'],['86','vinh_long','Vĩnh Long'],['91','an_giang','An Giang'],['92','can_tho','Cần Thơ'],['96','ca_mau','Cà Mau']].map(([code,slug,name])=>({code,slug,name,url:`${BASE}/${code}_${slug}/${code}_${slug}.geojson`}));
const metaByCode=new Map(provinces.map(p=>[p.code,p]));
const km={'04':'≈ 280 KM','08':'≈ 130 KM','11':'≈ 455 KM','12':'≈ 450 KM','14':'≈ 320 KM','15':'≈ 290 KM','19':'≈ 75 KM','20':'≈ 155 KM','22':'≈ 200 KM','24':'≈ 40 KM','25':'≈ 90 KM','31':'≈ 120 KM','33':'≈ 60 KM'};
const routeCodes=['08','04','12','15','19','11','20','14','25','24','22','31','33'];
const bias={'12':-40,'11':-25,'14':25,'15':-18,'08':18,'04':-15,'19':12,'20':22,'25':16,'24':-10,'22':-28,'31':15,'33':24};
const palette=['#f9d69a','#d9edb7','#ffeaa2','#f8c9aa','#cfe6b5','#efc6e7','#f0dda4','#bfe3cf','#f8c8a4'];
const GEO={minLon:101.7,maxLon:110.7,minLat:7.4,maxLat:23.7},PLOT={x:350,y:18,w:700,h:954};
const state={selectedProvince:null,selectedLine:null,features:new Map(),styles:new Map(),labels:new Map(),labelConfig:new Map(),basePoints:new Map(),lines:[],hanoi:{x:null,y:null},pickup:{x:36,y:730},transform:{x:0,y:0,k:1},pan:null,drag:null,drawMode:null,drawStart:null};
const $=id=>document.getElementById(id),svg=$('mapSvg'),defs=$('defs'),viewport=$('viewport'),mapLayer=$('mapLayer'),lineLayer=$('lineLayer'),labelLayer=$('labelLayer'),markerLayer=$('markerLayer'),handleLayer=$('handleLayer'),pickupLayer=$('pickupLayer'),previewLayer=$('previewLayer'),tooltip=$('tooltip');
const el=(tag,a={})=>{const n=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function project([lon,lat]){return[PLOT.x+(lon-GEO.minLon)/(GEO.maxLon-GEO.minLon)*PLOT.w,PLOT.y+(GEO.maxLat-lat)/(GEO.maxLat-GEO.minLat)*PLOT.h]}
function ringPath(r){return r&&r.length?'M'+r.map((p,i)=>{const[x,y]=project(p);return`${i?'L':''}${x.toFixed(2)},${y.toFixed(2)}`}).join('')+'Z':''}
function pathData(g){if(g.type==='Polygon')return g.coordinates.map(ringPath).join('');if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map(ringPath)).join('');return''}
function projectedOuterRings(g){if(g.type==='Polygon')return[g.coordinates[0].map(project)];if(g.type==='MultiPolygon')return g.coordinates.map(p=>p[0].map(project));return[]}
function ringArea(r){let a=0;for(let i=0,j=r.length-1;i<r.length;j=i++)a+=r[j][0]*r[i][1]-r[i][0]*r[j][1];return Math.abs(a/2)}
function largestRing(g){return projectedOuterRings(g).sort((a,b)=>ringArea(b)-ringArea(a))[0]||[]}
function bboxRing(r){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;r.forEach(([x,y])=>{minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)});return{minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY,cx:(minX+maxX)/2,cy:(minY+maxY)/2}}
function pointInRing(p,r){let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const xi=r[i][0],yi=r[i][1],xj=r[j][0],yj=r[j][1];if(((yi>p[1])!==(yj>p[1]))&&(p[0]<(xj-xi)*(p[1]-yi)/(yj-yi)+xi))inside=!inside}return inside}
function segDist(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1];if(!dx&&!dy)return Math.hypot(p[0]-a[0],p[1]-a[1]);let t=((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy);t=clamp(t,0,1);return Math.hypot(p[0]-(a[0]+t*dx),p[1]-(a[1]+t*dy))}
function edgeDist(p,r){let d=Infinity;for(let i=0,j=r.length-1;i<r.length;j=i++)d=Math.min(d,segDist(p,r[j],r[i]));return d}
function interiorPoint(g){const r=largestRing(g),b=bboxRing(r);let best=[b.cx,b.cy],score=-Infinity;for(let iy=1;iy<26;iy++)for(let ix=1;ix<26;ix++){const p=[b.minX+b.w*ix/26,b.minY+b.h*iy/26];if(pointInRing(p,r)){const s=edgeDist(p,r)-Math.hypot(p[0]-b.cx,p[1]-b.cy)*.015;if(s>score){score=s;best=p}}}return best}
function defaultLines(name,code){const up=name.toUpperCase();const manual={'08':['TUYÊN','QUANG'],'19':['THÁI','NGUYÊN'],'24':['BẮC','NINH'],'31':['HẢI','PHÒNG'],'33':['HƯNG','YÊN'],'37':['NINH','BÌNH'],'48':['ĐÀ','NẴNG'],'51':['QUẢNG','NGÃI'],'56':['KHÁNH','HÒA'],'79':['TP. HỒ CHÍ','MINH'],'82':['ĐỒNG','THÁP'],'86':['VĨNH','LONG'],'91':['AN','GIANG'],'92':['CẦN','THƠ']};return manual[code]||[up]}
function defaultStyle(i,code){return{fill:code==='01'?'#efc1df':palette[i%palette.length],stroke:'#40464b',hidden:false,showLabel:true}}
function defaultLabel(code){const m=metaByCode.get(code),p=state.basePoints.get(code)||[700,500];return{text:defaultLines(m.name,code).join('\n'),fontSize:10,fontWeight:700,color:'#111111',x:p[0],y:p[1],pinDx:0,pinDy:0}}
function getLabel(code){if(!state.labelConfig.has(code))state.labelConfig.set(code,defaultLabel(code));return state.labelConfig.get(code)}
function labelLines(cfg){const a=String(cfg.text||'').split('\n').map(s=>s.trim()).filter(Boolean).slice(0,4);return a.length?a:['']}
function pinRelativeY(code){const c=getLabel(code),lines=labelLines(c);return lines.length*c.fontSize*.58+7+c.pinDy}
function getPinPoint(code){const c=getLabel(code);return[c.x+c.pinDx,c.y+pinRelativeY(code)]}
function getHanoiPoint(){if(state.hanoi.x==null){const c=getLabel('01');return[c.x,c.y+11]}return[state.hanoi.x,state.hanoi.y]}
function save(){const data={labels:Object.fromEntries(state.labelConfig),styles:Object.fromEntries(state.styles),lines:state.lines,hanoi:state.hanoi,pickup:state.pickup,show:{labels:$('showLabels').checked,routes:$('showRoutes').checked,km:$('showKm').checked,pickup:$('showPickup').checked}};localStorage.setItem(STORE,JSON.stringify(data))}
function loadSaved(){try{const current=localStorage.getItem(STORE);if(current)return JSON.parse(current);const old=localStorage.getItem(OLD_STORE);return old?JSON.parse(old):null}catch{return null}}
function applySaved(data){if(!data)return;if(data.labels)Object.entries(data.labels).forEach(([k,v])=>state.labelConfig.set(k,v));if(data.styles)Object.entries(data.styles).forEach(([k,v])=>state.styles.set(k,v));if(Array.isArray(data.lines))state.lines=data.lines;if(data.hanoi)state.hanoi=data.hanoi;if(data.pickup)state.pickup=data.pickup;if(data.show){$('showLabels').checked=data.show.labels!==false;$('showRoutes').checked=data.show.routes!==false;$('showKm').checked=data.show.km!==false;$('showPickup').checked=data.show.pickup!==false}}
function ensureDefaultRoutes(){const existing=new Set(state.lines.filter(x=>x.builtin).map(x=>x.id));routeCodes.forEach(code=>{const id='route-'+code;if(!existing.has(id))state.lines.push({id,builtin:true,code,kind:'curve',arrow:true,color:'#e51d49',width:2,bend:bias[code]||0,startAnchor:{type:'pin',code},endAnchor:{type:'hanoi'}})})}
function resolveEnd(line,which){const a=line[which+'Anchor'];if(a?.type==='pin')return getPinPoint(a.code);if(a?.type==='hanoi')return getHanoiPoint();return line[which]||[700,500]}
function curveControl(line,s,e){if(line.ctrl)return line.ctrl;const dx=e[0]-s[0],dy=e[1]-s[1],len=Math.hypot(dx,dy)||1,mx=(s[0]+e[0])/2,my=(s[1]+e[1])/2;return[mx-dy/len*(line.bend||0),my+dx/len*(line.bend||0)]}
function calcBend(s,e,c){const dx=e[0]-s[0],dy=e[1]-s[1],len=Math.hypot(dx,dy)||1,mx=(s[0]+e[0])/2,my=(s[1]+e[1])/2;return((c[0]-mx)*(-dy/len)+(c[1]-my)*(dx/len))}
function renderProvince(meta,feature,index){const d=pathData(feature.geometry),p=el('path',{id:`province-${meta.code}`,d,'fill-rule':'evenodd',class:'province'});mapLayer.appendChild(p);state.features.set(meta.code,feature);state.basePoints.set(meta.code,interiorPoint(feature.geometry));if(!state.styles.has(meta.code))state.styles.set(meta.code,defaultStyle(index,meta.code));p.addEventListener('click',e=>{if(state.drawMode)return;e.stopPropagation();selectProvince(meta.code)});p.addEventListener('pointermove',e=>showTip(e,meta.name));p.addEventListener('pointerleave',()=>tooltip.style.opacity=0)}
function applyProvince(code){const p=$(`province-${code}`),s=state.styles.get(code);if(!p||!s)return;p.setAttribute('fill',s.fill);p.setAttribute('stroke',s.stroke);p.setAttribute('stroke-width','.9');p.classList.toggle('hidden',!!s.hidden);p.classList.toggle('active',state.selectedProvince===code)}
function renderLabels(){labelLayer.innerHTML='';provinces.forEach(meta=>{const s=state.styles.get(meta.code);if(!s||s.hidden||!s.showLabel||!$('showLabels').checked)return;const c=getLabel(meta.code),lines=labelLines(c),g=el('g',{class:'label-group','data-code':meta.code,transform:`translate(${c.x} ${c.y})`});const lineH=c.fontSize*1.05,startY=-(lines.length-1)*lineH/2;lines.forEach((line,i)=>{const t=el('text',{x:0,y:startY+i*lineH,class:'province-name','font-size':c.fontSize,'font-weight':c.fontWeight,fill:c.color,'data-code':meta.code});t.textContent=line;t.addEventListener('pointerdown',startLabelDrag);t.addEventListener('click',e=>{if(state.drawMode)return;e.stopPropagation();selectProvince(meta.code)});g.appendChild(t)});if(km[meta.code]){const pg=el('g',{class:'pin-group','data-code':meta.code,transform:`translate(${c.pinDx} ${pinRelativeY(meta.code)})`});const po=el('circle',{cx:0,cy:0,r:4.2,class:'pin-o'}),pi=el('circle',{cx:0,cy:0,r:2.2,class:'pin-i'});pg.append(po,pi);pg.addEventListener('pointerdown',startPinDrag);if($('showKm').checked){const dt=el('text',{x:0,y:12,class:'province-distance','font-size':7.5});dt.textContent=km[meta.code];pg.appendChild(dt)}g.appendChild(pg)}labelLayer.appendChild(g)});renderLines()}
function renderHanoi(){markerLayer.innerHTML='';const[x,y]=getHanoiPoint(),g=el('g',{class:'hanoi-marker',transform:`translate(${x} ${y})`});g.append(el('circle',{cx:0,cy:0,r:8,fill:'#e52b3d',stroke:'#fff','stroke-width':'1.8'}),el('polygon',{points:star(0,0,4.6,2),fill:'#fff'}));g.addEventListener('pointerdown',startHanoiDrag);markerLayer.appendChild(g)}
function star(cx,cy,r1,r2){const a=[];for(let i=0;i<10;i++){const ang=-Math.PI/2+i*Math.PI/5,r=i%2?r2:r1;a.push(`${cx+Math.cos(ang)*r},${cy+Math.sin(ang)*r}`)}return a.join(' ')}
function renderPickup(){pickupLayer.innerHTML='';if(!$('showPickup').checked)return;const{x,y}=state.pickup,g=el('g',{class:'pickup-card',transform:`translate(${x} ${y})`});g.append(el('rect',{x:0,y:0,width:365,height:205,rx:7,fill:'#fff0c9',stroke:'#555','stroke-width':'3'}),el('circle',{cx:47,cy:-2,r:18,fill:'#ed6b75',stroke:'#555','stroke-width':'4'}),el('path',{d:'M60 11L80 32',stroke:'#555','stroke-width':'6','stroke-linecap':'round'}));const title=el('text',{x:182,y:65,'text-anchor':'middle','font-family':'Roboto','font-size':'22','font-weight':'700'});title.textContent='ĐIỂM ĐÓN TẠI HÀ NỘI';g.appendChild(title);[['📍  Nhà hát Lớn Hà Nội',102,'700'],['◷  Thời gian đón: 05h30',135,'700'],['Quý khách vui lòng có mặt trước 15 phút.',170,'500']].forEach(([tx,yy,w])=>{const t=el('text',{x:20,y:yy,'font-family':'Roboto','font-size':'16','font-weight':w});t.textContent=tx;g.appendChild(t)});g.addEventListener('pointerdown',startPickupDrag);pickupLayer.appendChild(g)}
function renderLines(){lineLayer.innerHTML='';state.lines.forEach(line=>{if(line.builtin&&!$('showRoutes').checked)return;const s=resolveEnd(line,'start'),e=resolveEnd(line,'end'),p=el('path',{class:'editor-line'+(state.selectedLine===line.id?' selected':''),'data-id':line.id,stroke:line.color||'#e51d49','stroke-width':line.width||2});if(line.arrow)p.setAttribute('marker-end','url(#arrow)');if(line.kind==='curve'){const c=curveControl(line,s,e);p.setAttribute('d',`M${s[0]},${s[1]} Q${c[0]},${c[1]} ${e[0]},${e[1]}`)}else p.setAttribute('d',`M${s[0]},${s[1]} L${e[0]},${e[1]}`);p.addEventListener('pointerdown',startLineDrag);p.addEventListener('click',ev=>{if(state.drawMode)return;ev.stopPropagation();selectLine(line.id)});lineLayer.appendChild(p)});renderHandles()}
function renderHandles(){handleLayer.innerHTML='';const line=getSelectedLine();if(!line)return;const s=resolveEnd(line,'start'),e=resolveEnd(line,'end');handleLayer.appendChild(el('line',{x1:s[0],y1:s[1],x2:e[0],y2:e[1],class:'handle-link'}));const hs=el('circle',{cx:s[0],cy:s[1],r:6,class:'handle','data-handle':'start'}),he=el('circle',{cx:e[0],cy:e[1],r:6,class:'handle','data-handle':'end'});hs.addEventListener('pointerdown',startHandleDrag);he.addEventListener('pointerdown',startHandleDrag);handleLayer.append(hs,he);if(line.kind==='curve'){const c=curveControl(line,s,e),hc=el('circle',{cx:c[0],cy:c[1],r:6.5,class:'handle ctrl','data-handle':'ctrl'});hc.addEventListener('pointerdown',startHandleDrag);handleLayer.appendChild(hc)}}
function getSelectedLine(){return state.lines.find(x=>x.id===state.selectedLine)||null}
function selectProvince(code){state.selectedProvince=code;state.selectedLine=null;provinces.forEach(p=>applyProvince(p.code));syncProvinceControls();syncLineControls();renderLines()}
function selectLine(id){state.selectedLine=id;state.selectedProvince=null;provinces.forEach(p=>applyProvince(p.code));syncLineControls();renderLines()}
function syncProvinceControls(){const code=state.selectedProvince;if(!code)return;const m=metaByCode.get(code),s=state.styles.get(code),c=getLabel(code);$('selectedCard').innerHTML=`<b>${m.name}</b><br>Mã tỉnh: ${code}`;$('nameInput').value=c.text;$('fontSize').value=c.fontSize;$('fontSizeRange').value=c.fontSize;$('fontWeight').value=String(c.fontWeight);$('textColor').value=c.color;$('fillColor').value=s.fill;$('strokeColor').value=s.stroke;$('showSelectedLabel').checked=s.showLabel;$('hideSelected').checked=s.hidden}
function syncLineControls(){const line=getSelectedLine();$('lineEmpty').style.display=line?'none':'';$('lineEditor').style.display=line?'':'none';if(!line)return;$('lineColor').value=line.color||'#e51d49';$('lineWidth').value=line.width||2;$('lineArrow').checked=!!line.arrow;const s=resolveEnd(line,'start'),e=resolveEnd(line,'end'),b=line.kind==='curve'?Math.round(line.ctrl?calcBend(s,e,line.ctrl):(line.bend||0)):0;$('lineBend').value=b;$('lineBendRange').value=b;$('lineBend').disabled=line.kind!=='curve';$('lineBendRange').disabled=line.kind!=='curve'}
function populate(q=''){const sel=$('provinceSelect'),cur=state.selectedProvince,t=q.trim().toLocaleLowerCase('vi');sel.innerHTML='';provinces.filter(p=>p.name.toLocaleLowerCase('vi').includes(t)).forEach(p=>{const o=document.createElement('option');o.value=p.code;o.textContent=`${p.code} — ${p.name}`;sel.appendChild(o)});if(cur)sel.value=cur}
function showTip(e,text){const r=$('canvas').getBoundingClientRect();tooltip.textContent=text;tooltip.style.left=e.clientX-r.left+'px';tooltip.style.top=e.clientY-r.top+'px';tooltip.style.opacity=1}
function clientToSvg(e){const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const out=pt.matrixTransform(svg.getScreenCTM().inverse());return[out.x,out.y]}
function clientToWorld(e){const[x,y]=clientToSvg(e),t=state.transform;return[(x-t.x)/t.k,(y-t.y)/t.k]}
function startLabelDrag(e){if(state.drawMode||!$('dragLabel').checked)return;e.stopPropagation();const code=e.currentTarget.dataset.code;selectProvince(code);const c=getLabel(code),p=clientToWorld(e);state.drag={type:'label',code,dx:p[0]-c.x,dy:p[1]-c.y};svg.setPointerCapture(e.pointerId)}
function startPinDrag(e){if(state.drawMode)return;e.stopPropagation();const code=e.currentTarget.dataset.code;selectProvince(code);const c=getLabel(code),p=clientToWorld(e),pin=getPinPoint(code);state.drag={type:'pin',code,dx:p[0]-pin[0],dy:p[1]-pin[1]};svg.setPointerCapture(e.pointerId)}
function startHanoiDrag(e){if(state.drawMode)return;e.stopPropagation();const p=clientToWorld(e),h=getHanoiPoint();state.drag={type:'hanoi',dx:p[0]-h[0],dy:p[1]-h[1]};svg.setPointerCapture(e.pointerId)}
function startPickupDrag(e){if(state.drawMode)return;e.stopPropagation();const p=clientToSvg(e);state.drag={type:'pickup',dx:p[0]-state.pickup.x,dy:p[1]-state.pickup.y};svg.setPointerCapture(e.pointerId)}
function startHandleDrag(e){e.stopPropagation();const line=getSelectedLine();if(!line)return;state.drag={type:'handle',which:e.currentTarget.dataset.handle};svg.setPointerCapture(e.pointerId)}
function startLineDrag(e){if(state.drawMode)return;e.stopPropagation();const id=e.currentTarget.dataset.id;selectLine(id);const line=getSelectedLine();if(!line)return;const p=clientToWorld(e),s=resolveEnd(line,'start'),en=resolveEnd(line,'end'),c=line.kind==='curve'?curveControl(line,s,en):null;state.drag={type:'line',px:p[0],py:p[1],start:[...s],end:[...en],ctrl:c?[...c]:null};svg.setPointerCapture(e.pointerId)}
function onPointerMove(e){if(state.drag){if(state.drag.type==='pickup'){const p=clientToSvg(e);state.pickup.x=p[0]-state.drag.dx;state.pickup.y=p[1]-state.drag.dy;renderPickup();return}const p=clientToWorld(e);if(state.drag.type==='label'){const c=getLabel(state.drag.code);c.x=p[0]-state.drag.dx;c.y=p[1]-state.drag.dy;renderLabels();renderHanoi();return}if(state.drag.type==='pin'){const c=getLabel(state.drag.code),target=[p[0]-state.drag.dx,p[1]-state.drag.dy],relY=labelLines(c).length*c.fontSize*.58+7;c.pinDx=target[0]-c.x;c.pinDy=target[1]-c.y-relY;renderLabels();return}if(state.drag.type==='hanoi'){state.hanoi.x=p[0]-state.drag.dx;state.hanoi.y=p[1]-state.drag.dy;renderHanoi();renderLines();return}if(state.drag.type==='handle'){const line=getSelectedLine();if(!line)return;if(state.drag.which==='start'){line.startAnchor=null;line.start=p;line.ctrl=null}else if(state.drag.which==='end'){line.endAnchor=null;line.end=p;line.ctrl=null}else{line.ctrl=p;const s=resolveEnd(line,'start'),en=resolveEnd(line,'end');line.bend=calcBend(s,en,p)}renderLines();syncLineControls();return}if(state.drag.type==='line'){const line=getSelectedLine();if(!line)return;const dx=p[0]-state.drag.px,dy=p[1]-state.drag.py;line.startAnchor=null;line.endAnchor=null;line.start=[state.drag.start[0]+dx,state.drag.start[1]+dy];line.end=[state.drag.end[0]+dx,state.drag.end[1]+dy];if(line.kind==='curve'&&state.drag.ctrl)line.ctrl=[state.drag.ctrl[0]+dx,state.drag.ctrl[1]+dy];renderLines();syncLineControls();return}}
if(state.pan){const p=clientToSvg(e);state.transform.x=state.pan.tx+(p[0]-state.pan.x);state.transform.y=state.pan.ty+(p[1]-state.pan.y);updateTransform();return}
if(state.drawMode&&state.drawStart){const p=clientToWorld(e);previewLayer.innerHTML='';const path=el('path',{class:'draw-preview'});if(state.drawMode.includes('curve')){const s=state.drawStart,dx=p[0]-s[0],dy=p[1]-s[1],len=Math.hypot(dx,dy)||1,c=[(s[0]+p[0])/2-dy/len*45,(s[1]+p[1])/2+dx/len*45];path.setAttribute('d',`M${s[0]},${s[1]} Q${c[0]},${c[1]} ${p[0]},${p[1]}`)}else path.setAttribute('d',`M${state.drawStart[0]},${state.drawStart[1]} L${p[0]},${p[1]}`);previewLayer.appendChild(path)}}
function onPointerUp(e){if(state.drag){state.drag=null;try{svg.releasePointerCapture(e.pointerId)}catch{}save();return}if(state.pan){state.pan=null;try{svg.releasePointerCapture(e.pointerId)}catch{}}}
function onSvgPointerDown(e){if(e.button!==0)return;if(state.drawMode){if(e.target.closest?.('.handle,.province-name,.pin-group,.hanoi-marker'))return;e.preventDefault();const p=clientToWorld(e);if(!state.drawStart){state.drawStart=p;$('drawNote').textContent='Đã chọn điểm đầu — bấm điểm thứ hai.';previewLayer.innerHTML=''}else{createDrawnLine(state.drawStart,p,state.drawMode);state.drawStart=null;previewLayer.innerHTML='';$('drawNote').textContent='Đã vẽ xong. Tiếp tục bấm 2 điểm để vẽ thêm.'}return}if(e.target===svg||e.target.tagName==='rect'){const p=clientToSvg(e);state.pan={x:p[0],y:p[1],tx:state.transform.x,ty:state.transform.y};svg.setPointerCapture(e.pointerId)}}
function createDrawnLine(s,e,mode){const curve=mode.includes('curve'),arrow=mode.startsWith('arrow-'),id='custom-'+Date.now()+'-'+Math.floor(Math.random()*9999),line={id,builtin:false,kind:curve?'curve':'line',arrow,color:'#e51d49',width:2,start:s,end:e,bend:curve?45:0};state.lines.push(line);selectLine(id);save()}
function setDrawMode(mode){state.drawMode=mode;state.drawStart=null;previewLayer.innerHTML='';document.querySelectorAll('.draw-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('selectMode').classList.toggle('active',!mode);const names={'arrow-curve':'Vẽ mũi tên cong','arrow-line':'Vẽ mũi tên thẳng','curve':'Vẽ đường cong','line':'Vẽ đường thẳng'};$('drawNote').textContent=mode?`${names[mode]}: bấm điểm đầu rồi bấm điểm cuối.`:'Chế độ chọn/di chuyển.'}
function updateTransform(){const t=state.transform;viewport.setAttribute('transform',`translate(${t.x} ${t.y}) scale(${t.k})`)}
function zoom(f,cx=700,cy=500){const t=state.transform,nk=clamp(t.k*f,.55,7),wx=(cx-t.x)/t.k,wy=(cy-t.y)/t.k;t.x=cx-wx*nk;t.y=cy-wy*nk;t.k=nk;updateTransform()}
function fit(){state.transform={x:0,y:0,k:1};updateTransform()}
function downloadText(data,name,type='text/plain'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function exportSvg(){const c=svg.cloneNode(true);const h=c.querySelector('#handleLayer'),pr=c.querySelector('#previewLayer');if(h)h.remove();if(pr)pr.remove();c.querySelectorAll('.editor-line.selected').forEach(x=>x.classList.remove('selected'));const style=document.createElementNS(NS,'style');style.textContent='.province-name{font-family:Roboto,Arial,sans-serif;text-anchor:middle;stroke:none}.province-distance{font-family:Roboto,Arial,sans-serif;text-anchor:middle;font-weight:700;fill:#333}.editor-line{fill:none}.pin-o{fill:#fff8ea;stroke:#e51d49;stroke-width:1.8}.pin-i{fill:#e51d49}';c.insertBefore(style,c.firstChild);downloadText(new XMLSerializer().serializeToString(c),'ban-do-viet-nam-editor.svg','image/svg+xml')}
function resetAll(){if(!confirm('Khôi phục toàn bộ bản đồ về mặc định?'))return;localStorage.removeItem(STORE);location.reload()}
function exportConfig(){const data=localStorage.getItem(STORE)||JSON.stringify({});downloadText(data,'cau-hinh-ban-do-viet-nam.json','application/json')}
async function exportBrowserData(){
  const button=$('exportBrowserData'),oldText=button?.textContent;
  if(button){button.disabled=true;button.textContent='Đang gom dữ liệu…'}
  try{
    await window.__VN_PERSIST?.flush?.();
    const local={};
    for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key!=null)local[key]=localStorage.getItem(key)}
    const backups=await window.__VN_PERSIST?.getAllBackups?.()||[];
    const payload={format:'vn-map-browser-backup',version:1,exportedAt:new Date().toISOString(),origin:location.origin,localStorage:local,indexedDB:{database:'vn-map-editor-safe-storage',store:'backups',records:backups}};
    const date=new Date().toISOString().slice(0,10);
    downloadText(JSON.stringify(payload,null,2),`ban-do-viet-nam-toan-bo-du-lieu-${date}.json`,'application/json');
    const n=$('saveStatus');if(n){n.textContent=`✓ Đã xuất ${Object.keys(local).length} mục dữ liệu và ${backups.length} bản sao`;n.dataset.state='saved'}
  }catch(e){console.error(e);alert('Không xuất được toàn bộ dữ liệu: '+(e?.message||e))}
  finally{if(button){button.disabled=false;button.textContent=oldText}}
}
async function importBrowserDataFile(file){
  const button=$('importBrowserData'),oldText=button?.textContent,input=$('browserDataFile');
  if(button){button.disabled=true;button.textContent='Đang đọc bản sao lưu…'}
  try{
    if(!file||file.size>60*1024*1024)throw new Error('File không hợp lệ hoặc lớn hơn 60 MB.');
    const payload=JSON.parse(await file.text());
    if(payload?.format!=='vn-map-browser-backup'||payload?.version!==1||!payload.localStorage||typeof payload.localStorage!=='object'||Array.isArray(payload.localStorage))throw new Error('Đây không phải file “Xuất toàn bộ dữ liệu trình duyệt”.');
    const entries=Object.entries(payload.localStorage).filter(([key,value])=>typeof key==='string'&&typeof value==='string');
    if(!entries.length)throw new Error('File sao lưu không có dữ liệu localStorage.');
    const source=payload.origin&&payload.origin!==location.origin?`\nFile được xuất từ: ${payload.origin}\nTrang hiện tại: ${location.origin}`:'';
    if(!confirm(`Nhập ${entries.length} mục dữ liệu? Dữ liệu trùng tên trong trình duyệt hiện tại sẽ bị thay thế.${source}`))return;
    payload.localStorage['vn-map-tour-point-shapes-visible-v1']='1';
    try{const shapes=JSON.parse(payload.localStorage['vn-map-flag-shapes-v1']||'null');if(shapes&&typeof shapes==='object'){shapes.show=true;payload.localStorage['vn-map-flag-shapes-v1']=JSON.stringify(shapes)}}catch{}
    if(!window.__VN_PERSIST?.stageImport)throw new Error('Bộ nhập dữ liệu chưa tải xong. Hãy Ctrl+F5 rồi thử lại.');
    await window.__VN_PERSIST.stageImport(payload);
    alert('Đã chuẩn bị xong dữ liệu. Trang sẽ tải lại và áp dụng bản sao lưu trước khi các lớp ảnh khởi động.');
    location.reload();
  }catch(e){console.error(e);alert('Không nhập được toàn bộ dữ liệu: '+(e?.message||e))}
  finally{if(input)input.value='';if(button){button.disabled=false;button.textContent=oldText}}
}
function importConfigFile(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);localStorage.setItem(STORE,JSON.stringify(data));location.reload()}catch{alert('File cấu hình không hợp lệ.')}};r.readAsText(file)}
async function loadAll(){let done=0,failed=[];const q=[...provinces],workers=Array.from({length:6},async()=>{while(q.length){const meta=q.shift();try{const r=await fetch(meta.url,{cache:'force-cache'});if(!r.ok)throw Error(r.status);const gj=await r.json(),feature=gj.features?.[0];if(!feature)throw Error('empty');renderProvince(meta,feature,provinces.findIndex(p=>p.code===meta.code))}catch(err){failed.push(meta.name);console.error(meta.name,err)}done++;$('progress').style.width=done/provinces.length*100+'%';$('progressText').textContent=`${done} / ${provinces.length}`}});await Promise.all(workers);const saved=loadSaved();applySaved(saved);provinces.forEach((p,i)=>{const ds=defaultStyle(i,p.code),oldStyle=state.styles.get(p.code)||{};state.styles.set(p.code,{...ds,...oldStyle});const dl=defaultLabel(p.code),oldLabel=state.labelConfig.get(p.code)||{};state.labelConfig.set(p.code,{...dl,...oldLabel,pinDx:Number(oldLabel.pinDx)||0,pinDy:Number(oldLabel.pinDy)||0,fontSize:clamp(Number(oldLabel.fontSize)||10,6,40),fontWeight:Number(oldLabel.fontWeight)||700,color:oldLabel.color||'#111111'});applyProvince(p.code)});ensureDefaultRoutes();renderLabels();renderHanoi();renderPickup();renderLines();$('loading').style.display='none';$('badge').textContent=failed.length?`Đã tải ${34-failed.length}/34 tỉnh`:'Đã tải đủ 34 tỉnh/thành';if(!failed.length)selectProvince('01');save();if(failed.length)alert('Không tải được: '+failed.join(', '))}
populate();
$('provinceSelect').addEventListener('change',e=>selectProvince(e.target.value));$('search').addEventListener('input',e=>populate(e.target.value));
$('nameInput').addEventListener('input',e=>{if(!state.selectedProvince)return;getLabel(state.selectedProvince).text=e.target.value;renderLabels();save()});
function setFontSize(v){if(!state.selectedProvince)return;v=clamp(Number(v)||10,6,40);const c=getLabel(state.selectedProvince);c.fontSize=v;$('fontSize').value=v;$('fontSizeRange').value=v;renderLabels();save()}
$('fontSize').addEventListener('input',e=>setFontSize(e.target.value));$('fontSizeRange').addEventListener('input',e=>setFontSize(e.target.value));
$('fontWeight').addEventListener('change',e=>{if(!state.selectedProvince)return;getLabel(state.selectedProvince).fontWeight=Number(e.target.value);renderLabels();save()});$('textColor').addEventListener('input',e=>{if(!state.selectedProvince)return;getLabel(state.selectedProvince).color=e.target.value;renderLabels();save()});
$('resetLabelPos').addEventListener('click',()=>{if(!state.selectedProvince)return;const code=state.selectedProvince,b=state.basePoints.get(code),c=getLabel(code);c.x=b[0];c.y=b[1];c.pinDx=0;c.pinDy=0;if(code==='01'){state.hanoi={x:null,y:null}}renderLabels();renderHanoi();save()});
$('resetLabelStyle').addEventListener('click',()=>{if(!state.selectedProvince)return;const code=state.selectedProvince,d=defaultLabel(code);d.x=getLabel(code).x;d.y=getLabel(code).y;d.pinDx=getLabel(code).pinDx;d.pinDy=getLabel(code).pinDy;state.labelConfig.set(code,d);syncProvinceControls();renderLabels();save()});
$('fillColor').addEventListener('input',e=>{if(!state.selectedProvince)return;state.styles.get(state.selectedProvince).fill=e.target.value;applyProvince(state.selectedProvince);save()});$('strokeColor').addEventListener('input',e=>{if(!state.selectedProvince)return;state.styles.get(state.selectedProvince).stroke=e.target.value;applyProvince(state.selectedProvince);save()});$('showSelectedLabel').addEventListener('change',e=>{if(!state.selectedProvince)return;state.styles.get(state.selectedProvince).showLabel=e.target.checked;renderLabels();save()});$('hideSelected').addEventListener('change',e=>{if(!state.selectedProvince)return;state.styles.get(state.selectedProvince).hidden=e.target.checked;applyProvince(state.selectedProvince);renderLabels();save()});
document.querySelectorAll('.draw-btn').forEach(b=>b.addEventListener('click',()=>setDrawMode(b.dataset.mode)));$('cancelDraw').addEventListener('click',()=>setDrawMode(null));$('selectMode').addEventListener('click',()=>setDrawMode(null));
$('lineColor').addEventListener('input',e=>{const l=getSelectedLine();if(!l)return;l.color=e.target.value;renderLines();save()});$('lineWidth').addEventListener('input',e=>{const l=getSelectedLine();if(!l)return;l.width=clamp(Number(e.target.value)||2,.5,12);renderLines();save()});$('lineArrow').addEventListener('change',e=>{const l=getSelectedLine();if(!l)return;l.arrow=e.target.checked;renderLines();save()});
function setBend(v){const l=getSelectedLine();if(!l||l.kind!=='curve')return;v=clamp(Number(v)||0,-250,250);l.bend=v;l.ctrl=null;$('lineBend').value=v;$('lineBendRange').value=v;renderLines();save()}
$('lineBend').addEventListener('input',e=>setBend(e.target.value));$('lineBendRange').addEventListener('input',e=>setBend(e.target.value));
$('deleteLine').addEventListener('click',()=>{const l=getSelectedLine();if(!l)return;if(l.builtin&&!confirm('Xóa mũi tên mặc định này?'))return;state.lines=state.lines.filter(x=>x.id!==l.id);state.selectedLine=null;syncLineControls();renderLines();save()});$('duplicateLine').addEventListener('click',()=>{const l=getSelectedLine();if(!l)return;const n=JSON.parse(JSON.stringify(l));n.id='copy-'+Date.now();n.builtin=false;n.code=null;n.startAnchor=null;n.endAnchor=null;const s=resolveEnd(l,'start'),e=resolveEnd(l,'end');n.start=[s[0]+15,s[1]+15];n.end=[e[0]+15,e[1]+15];if(l.kind==='curve'){const c=curveControl(l,s,e);n.ctrl=[c[0]+15,c[1]+15]}state.lines.push(n);selectLine(n.id);save()});
$('showLabels').addEventListener('change',()=>{renderLabels();save()});$('showRoutes').addEventListener('change',()=>{renderLines();save()});$('showKm').addEventListener('change',()=>{renderLabels();save()});$('showPickup').addEventListener('change',()=>{renderPickup();save()});$('exportAll').addEventListener('click',exportSvg);$('resetAll').addEventListener('click',resetAll);$('exportConfig').addEventListener('click',exportConfig);$('exportBrowserData').addEventListener('click',exportBrowserData);$('importBrowserData').addEventListener('click',()=>$('browserDataFile').click());$('browserDataFile').addEventListener('change',e=>{if(e.target.files[0])importBrowserDataFile(e.target.files[0]);else e.target.value=''});$('importConfig').addEventListener('click',()=>$('configFile').click());$('configFile').addEventListener('change',e=>{if(e.target.files[0])importConfigFile(e.target.files[0])});
$('zoomIn').addEventListener('click',()=>zoom(1.22));$('zoomOut').addEventListener('click',()=>zoom(.82));$('fitMap').addEventListener('click',fit);
svg.addEventListener('pointerdown',onSvgPointerDown);svg.addEventListener('pointermove',onPointerMove);svg.addEventListener('pointerup',onPointerUp);svg.addEventListener('pointercancel',onPointerUp);svg.addEventListener('wheel',e=>{e.preventDefault();const[x,y]=clientToSvg(e);zoom(e.deltaY<0?1.12:.89,x,y)},{passive:false});svg.addEventListener('dblclick',()=>{if(!state.drawMode)fit()});svg.addEventListener('click',e=>{if(!state.drawMode&&e.target===svg){state.selectedLine=null;syncLineControls();renderLines()}});
window.addEventListener('keydown',e=>{if(e.key==='Escape')setDrawMode(null);if((e.key==='Delete'||e.key==='Backspace')&&state.selectedLine&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))$('deleteLine').click()});
loadAll();
})();
