(()=>{
'use strict';
const NS='http://www.w3.org/2000/svg';
const STORE='vn-map-flags-v1';
const $=id=>document.getElementById(id);
const svg=$('mapSvg'),viewport=$('viewport'),layer=$('flagLayer'),canvas=$('canvas');
if(!svg||!viewport||!layer)return;
const state={flags:[],selected:null,show:true,dragEnabled:true,drag:null,saveTimer:null};
const el=(tag,a={})=>{const n=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>n.setAttribute(k,v));return n};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const validColor=(v,d)=>/^#[0-9a-f]{6}$/i.test(v||'')?v:d;
function uid(){return'flag-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)}
function ensureExtraControls(){
  const editor=$('flagEditor');if(!editor)return;
  if(!$('flagPoleHeight')){
    const direction=$('flagDirection'),row=direction?.closest('.row');
    const label=document.createElement('label');label.style.marginTop='8px';label.textContent='Chiều cao cột cờ';
    const wrap=document.createElement('div');wrap.className='value-line';
    const range=document.createElement('input');range.type='range';range.id='flagPoleHeightRange';range.min='25';range.max='320';range.step='1';range.value='80';
    const num=document.createElement('input');num.type='number';num.id='flagPoleHeight';num.min='25';num.max='320';num.step='1';num.value='80';
    wrap.append(range,num);
    if(row){row.insertAdjacentElement('afterend',label);label.insertAdjacentElement('afterend',wrap)}else editor.prepend(label,wrap);
  }
  if(!$('restoreFlagImageRatio')){
    const lock=$('flagLockRatio')?.closest('label');
    if(lock){const b=document.createElement('button');b.id='restoreFlagImageRatio';b.type='button';b.className='btn';b.style.width='100%';b.style.marginTop='7px';b.textContent='Về đúng tỷ lệ ảnh gốc';lock.insertAdjacentElement('afterend',b)}
  }
  [['flagImageWRange',30,360],['flagImageW',30,360],['flagImageHRange',20,280],['flagImageH',20,280]].forEach(([id,min,max])=>{const n=$(id);if(n){n.min=String(min);n.max=String(max)}});
}
function normalizeFlag(f,i=0){
  const kind=f?.kind==='image'?'image':'triangle';
  let imageW=clamp(Number(f?.imageW)||96,30,360),imageH=clamp(Number(f?.imageH)||60,20,280);
  const bw=Number(f?.borderWidth),rawRatio=Number(f?.imageRatio),imageRatio=rawRatio>0?rawRatio:imageW/imageH;
  if(kind==='image'&&Math.abs(imageW/imageH-1)<.06&&Math.abs(imageRatio-1)>.08)imageH=clamp(imageW/imageRatio,20,280);
  const size=clamp(Number(f?.size)||34,12,120),defaultPole=kind==='image'?Math.max(imageH*1.75,80):size*1.75;
  return{id:String(f?.id||uid()),x:Number.isFinite(Number(f?.x))?Number(f.x):700+i*14,y:Number.isFinite(Number(f?.y))?Number(f.y):500+i*10,kind,size,poleHeight:clamp(Number(f?.poleHeight)||defaultPole,25,320),flagColor:validColor(f?.flagColor,'#e51d49'),poleColor:validColor(f?.poleColor,'#333333'),direction:f?.direction==='left'?'left':'right',imageSrc:String(f?.imageSrc||''),imageUrl:String(f?.imageUrl||''),imageW,imageH,imageRatio,lockRatio:f?.lockRatio!==false,imageFit:f?.imageFit==='cover'?'cover':'contain',borderColor:validColor(f?.borderColor,'#ffffff'),borderWidth:clamp(Number.isFinite(bw)?bw:1.5,0,8),radius:clamp(Number(f?.radius)||2,0,30)}
}
function load(){try{const d=JSON.parse(localStorage.getItem(STORE)||'{}');state.flags=Array.isArray(d.flags)?d.flags.map(normalizeFlag):[];state.show=d.show!==false;state.dragEnabled=d.dragEnabled!==false}catch{state.flags=[]}}
function save(flush=false){try{localStorage.setItem(STORE,JSON.stringify({version:3,flags:state.flags,show:state.show,dragEnabled:state.dragEnabled,updatedAt:Date.now()}))}catch(e){console.warn('Không lưu được cờ',e);setImageStatus('Dung lượng lưu cờ đã đầy. Hãy dùng ảnh nhỏ hơn.','error')}if(flush&&window.__VN_PERSIST?.flush)window.__VN_PERSIST.flush();else scheduleFlush()}
function scheduleFlush(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>window.__VN_PERSIST?.flush?.(),500)}
function selectedFlag(){return state.flags.find(f=>f.id===state.selected)||null}
function worldFromClient(e){const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const m=viewport.getScreenCTM();if(!m)return[700,500];const p=pt.matrixTransform(m.inverse());return[p.x,p.y]}
function visibleCenter(){const r=canvas?.getBoundingClientRect();if(!r)return[700,500];return worldFromClient({clientX:r.left+r.width/2,clientY:r.top+r.height/2})}
function imageBox(f){const dir=f.direction==='left'?-1:1,w=f.imageW,h=f.imageH,poleH=clamp(Number(f.poleHeight)||Math.max(h*1.75,80),25,320),x=dir<0?-w:0,y=-poleH;return{dir,w,h,poleH,x,y}}
function drawTriangleFlag(g,f){const s=f.size,poleH=clamp(Number(f.poleHeight)||s*1.75,25,320),flagH=s*.68,flagW=s,dir=f.direction==='left'?-1:1,minX=dir<0?-flagW-s*.25:-s*.25;g.appendChild(el('rect',{x:minX,y:-poleH-s*.12,width:flagW+s*.5,height:poleH+s*.38,class:'flag-hit'}));g.appendChild(el('line',{x1:0,y1:4,x2:0,y2:-poleH,class:'flag-pole',stroke:f.poleColor,'stroke-width':Math.max(1.7,s*.065)}));g.appendChild(el('polygon',{points:`0,${-poleH} ${dir*flagW},${-poleH+flagH*.48} 0,${-poleH+flagH}`,class:'flag-shape',fill:f.flagColor}));g.appendChild(el('circle',{cx:0,cy:4,r:Math.max(2.2,s*.095),class:'flag-base',fill:f.poleColor}))}
function drawImageFlag(g,f){const b=imageBox(f),pad=8,clipId='clip-'+f.id.replace(/[^a-zA-Z0-9_-]/g,'');g.appendChild(el('rect',{x:b.x-pad,y:b.y-pad,width:b.w+pad*2,height:b.poleH+pad+14,class:'flag-hit'}));g.appendChild(el('line',{x1:0,y1:5,x2:0,y2:-b.poleH,class:'flag-pole',stroke:f.poleColor,'stroke-width':Math.max(2,b.h*.045)}));const cp=el('clipPath',{id:clipId}),cr=el('rect',{x:b.x,y:b.y,width:b.w,height:b.h,rx:f.radius,ry:f.radius});cp.appendChild(cr);g.appendChild(cp);g.appendChild(el('rect',{x:b.x,y:b.y,width:b.w,height:b.h,rx:f.radius,ry:f.radius,fill:'#ffffff'}));if(f.imageSrc){const im=el('image',{x:b.x,y:b.y,width:b.w,height:b.h,href:f.imageSrc,'clip-path':`url(#${clipId})`,preserveAspectRatio:f.imageFit==='contain'?'xMidYMid meet':'xMidYMid slice'});g.appendChild(im)}else{const t=el('text',{x:b.x+b.w/2,y:b.y+b.h/2,class:'flag-image-placeholder','font-size':clamp(Math.min(b.w,b.h)*.22,9,24),fill:'#8a8177'});t.textContent='ẢNH';g.appendChild(t)}g.appendChild(el('rect',{x:b.x,y:b.y,width:b.w,height:b.h,rx:f.radius,ry:f.radius,fill:'none',stroke:f.borderColor,'stroke-width':f.borderWidth,class:'flag-image-border'}));g.appendChild(el('circle',{cx:0,cy:5,r:Math.max(2.5,b.h*.055),class:'flag-base',fill:f.poleColor}))}
function drawFlag(f){const g=el('g',{class:'flag-marker'+(f.id===state.selected?' selected':''),'data-id':f.id,transform:`translate(${f.x} ${f.y})`});if(f.kind==='image')drawImageFlag(g,f);else drawTriangleFlag(g,f);g.addEventListener('pointerdown',startDrag);g.addEventListener('click',e=>{e.stopPropagation();select(f.id)});return g}
function render(){layer.innerHTML='';layer.style.display=state.show?'':'none';if(state.show)state.flags.forEach(f=>layer.appendChild(drawFlag(f)));syncList();syncEditor()}
function syncList(){const s=$('flagSelect');if(!s)return;const cur=state.selected;s.innerHTML='';state.flags.forEach((f,i)=>{const o=document.createElement('option');o.value=f.id;o.textContent=`${f.kind==='image'?'Cờ ảnh':'Cờ tam giác'} ${i+1}`;s.appendChild(o)});if(cur)s.value=cur;const c=$('flagCount');if(c)c.textContent=`${state.flags.length} cờ trên bản đồ`;if($('showFlags'))$('showFlags').checked=state.show;if($('dragFlags'))$('dragFlags').checked=state.dragEnabled}
function syncEditor(){const f=selectedFlag(),empty=$('flagEmpty'),ed=$('flagEditor');if(empty)empty.style.display=f?'none':'';if(ed)ed.style.display=f?'':'none';if(!f)return;if($('flagType'))$('flagType').value=f.kind;$('flagSize').value=f.size;$('flagSizeRange').value=f.size;$('flagColor').value=f.flagColor;$('flagPoleColor').value=f.poleColor;$('flagX').value=Math.round(f.x);$('flagY').value=Math.round(f.y);$('flagDirection').value=f.direction;if($('flagPoleHeight'))$('flagPoleHeight').value=Math.round(f.poleHeight);if($('flagPoleHeightRange'))$('flagPoleHeightRange').value=f.poleHeight;if($('triangleFlagOptions'))$('triangleFlagOptions').style.display=f.kind==='triangle'?'':'none';if($('imageFlagOptions'))$('imageFlagOptions').style.display=f.kind==='image'?'':'none';if($('flagImageUrl'))$('flagImageUrl').value=f.imageUrl||(/^https?:/i.test(f.imageSrc)?f.imageSrc:'');if($('flagImageW'))$('flagImageW').value=Math.round(f.imageW);if($('flagImageWRange'))$('flagImageWRange').value=f.imageW;if($('flagImageH'))$('flagImageH').value=Math.round(f.imageH);if($('flagImageHRange'))$('flagImageHRange').value=f.imageH;if($('flagLockRatio'))$('flagLockRatio').checked=f.lockRatio;if($('flagImageFit'))$('flagImageFit').value=f.imageFit;if($('flagBorderColor'))$('flagBorderColor').value=f.borderColor;if($('flagBorderWidth'))$('flagBorderWidth').value=f.borderWidth;if($('flagRadius'))$('flagRadius').value=f.radius}
function setImageStatus(text,type=''){const n=$('flagImageStatus');if(!n)return;n.textContent=text;n.className='flag-image-status'+(type?' '+type:'')}
function select(id){state.selected=id;render()}
function addTriangleFlag(){const[x,y]=visibleCenter(),f=normalizeFlag({id:uid(),x,y,kind:'triangle',size:34,poleHeight:60,flagColor:'#e51d49',poleColor:'#333333'});state.flags.push(f);state.selected=f.id;save();render()}
function addImageFlag(){const[x,y]=visibleCenter(),f=normalizeFlag({id:uid(),x,y,kind:'image',imageW:96,imageH:60,poleHeight:115,lockRatio:true,imageFit:'contain',poleColor:'#333333'});state.flags.push(f);state.selected=f.id;save();render();setImageStatus('Chọn ảnh từ máy hoặc dán URL ảnh. Khung sẽ tự theo tỷ lệ ảnh gốc.','')}
function duplicateFlag(){const f=selectedFlag();if(!f)return;const n=normalizeFlag({...f,id:uid(),x:f.x+18,y:f.y+18});state.flags.push(n);state.selected=n.id;save();render()}
function deleteFlag(){const f=selectedFlag();if(!f)return;state.flags=state.flags.filter(x=>x.id!==f.id);state.selected=state.flags.at(-1)?.id||null;save(true);render()}
function clearFlags(){if(!state.flags.length)return;if(!confirm('Xóa toàn bộ cờ đánh dấu?'))return;state.flags=[];state.selected=null;save(true);render()}
function centerFlag(){const f=selectedFlag();if(!f)return;const[x,y]=visibleCenter();f.x=x;f.y=y;save();render()}
function setSize(v){const f=selectedFlag();if(!f)return;f.size=clamp(Number(v)||34,12,120);$('flagSize').value=f.size;$('flagSizeRange').value=f.size;save();render()}
function setPoleHeight(v){const f=selectedFlag();if(!f)return;f.poleHeight=clamp(Number(v)||80,25,320);if($('flagPoleHeight'))$('flagPoleHeight').value=f.poleHeight;if($('flagPoleHeightRange'))$('flagPoleHeightRange').value=f.poleHeight;save();render()}
function setImageDimension(axis,v){const f=selectedFlag();if(!f||f.kind!=='image')return;const value=axis==='w'?clamp(Number(v)||96,30,360):clamp(Number(v)||60,20,280);if(axis==='w'){f.imageW=value;if(f.lockRatio)f.imageH=clamp(value/(f.imageRatio||1.6),20,280)}else{f.imageH=value;if(f.lockRatio)f.imageW=clamp(value*(f.imageRatio||1.6),30,360)}save();render()}
function restoreImageRatio(){const f=selectedFlag();if(!f||f.kind!=='image')return;const ratio=Number(f.imageRatio)||1.6;f.lockRatio=true;f.imageH=clamp(f.imageW/ratio,20,280);save();render();setImageStatus('✓ Đã đưa khung về đúng tỷ lệ ảnh gốc.','ok')}
function startDrag(e){if(!state.dragEnabled)return;e.preventDefault();e.stopPropagation();const id=e.currentTarget.dataset.id;state.selected=id;const f=selectedFlag();if(!f)return;const p=worldFromClient(e);state.drag={id,dx:p[0]-f.x,dy:p[1]-f.y,pointerId:e.pointerId};try{svg.setPointerCapture(e.pointerId)}catch{}render()}
function moveDrag(e){if(!state.drag)return;const f=state.flags.find(x=>x.id===state.drag.id);if(!f)return;const p=worldFromClient(e);f.x=p[0]-state.drag.dx;f.y=p[1]-state.drag.dy;save(false);render()}
function endDrag(){if(!state.drag)return;const pointerId=state.drag.pointerId;state.drag=null;try{svg.releasePointerCapture(pointerId)}catch{}save(true);render()}
function setPos(axis,v){const f=selectedFlag();if(!f)return;const n=Number(v);if(!Number.isFinite(n))return;f[axis]=n;save();render()}
function loadHtmlImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Không đọc được ảnh'));im.src=src})}
async function optimizeBlob(blob){if(!blob?.type?.startsWith('image/'))throw new Error('File không phải hình ảnh.');if(blob.size>18*1024*1024)throw new Error('Ảnh quá lớn. Vui lòng chọn ảnh dưới 18 MB.');const url=URL.createObjectURL(blob);try{const im=await loadHtmlImage(url),max=1200,scale=Math.min(1,max/Math.max(im.naturalWidth||1,im.naturalHeight||1)),w=Math.max(1,Math.round(im.naturalWidth*scale)),h=Math.max(1,Math.round(im.naturalHeight*scale)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(im,0,0,w,h);let data=c.toDataURL('image/webp',.86);if(!data.startsWith('data:image/webp'))data=c.toDataURL('image/png');return{data,width:im.naturalWidth,height:im.naturalHeight}}finally{URL.revokeObjectURL(url)}}
function applyImageData(f,data,width,height,sourceUrl=''){f.kind='image';f.imageSrc=data;f.imageUrl=sourceUrl;const ratio=(Number(width)||f.imageW)/(Number(height)||f.imageH);if(Number.isFinite(ratio)&&ratio>0){f.imageRatio=ratio;f.lockRatio=true;const targetW=clamp(Number(f.imageW)||96,30,360);f.imageW=targetW;f.imageH=clamp(targetW/ratio,20,280)}save(true);render()}
async function chooseLocalFile(file){const f=selectedFlag();if(!f||!file)return;try{setImageStatus('Đang xử lý ảnh từ máy…','');const out=await optimizeBlob(file);applyImageData(f,out.data,out.width,out.height,'');setImageStatus(`✓ Đã lưu ảnh từ máy: ${file.name}. Khung đã theo tỷ lệ ảnh gốc.`,'ok')}catch(e){setImageStatus(e.message||String(e),'error')}}
async function useImageUrl(){const f=selectedFlag();if(!f)return;const url=String($('flagImageUrl')?.value||'').trim();if(!url){setImageStatus('Hãy nhập URL ảnh.','warn');return}if(!/^https?:\/\//i.test(url)&&!/^data:image\//i.test(url)){setImageStatus('URL ảnh phải bắt đầu bằng http:// hoặc https://','error');return}try{setImageStatus('Đang tải ảnh từ URL để nhúng vào bản đồ…','');if(/^data:image\//i.test(url)){const im=await loadHtmlImage(url);applyImageData(f,url,im.naturalWidth,im.naturalHeight,'');setImageStatus('✓ Đã dùng ảnh data URL và giữ đúng tỷ lệ.','ok');return}const r=await fetch(url,{mode:'cors',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const blob=await r.blob(),out=await optimizeBlob(blob);applyImageData(f,out.data,out.width,out.height,url);setImageStatus('✓ Đã tải và nhúng ảnh URL, giữ đúng tỷ lệ gốc.','ok')}catch(e){f.kind='image';f.imageSrc=url;f.imageUrl=url;try{const im=await loadHtmlImage(url),ratio=(im.naturalWidth||1)/(im.naturalHeight||1);if(ratio>0){f.imageRatio=ratio;f.lockRatio=true;f.imageH=clamp(f.imageW/ratio,20,280)}}catch{}save(true);render();setImageStatus('Không thể nhúng do CORS; đang dùng URL trực tiếp và vẫn cố giữ tỷ lệ ảnh. Xuất PNG/PDF phụ thuộc máy chủ ảnh.','warn')}}
function clearFlagImage(){const f=selectedFlag();if(!f)return;f.imageSrc='';f.imageUrl='';save(true);render();setImageStatus('Đã xóa ảnh khỏi cờ.','')}
ensureExtraControls();load();
$('addFlag')?.addEventListener('click',addTriangleFlag);$('addImageFlag')?.addEventListener('click',addImageFlag);$('duplicateFlag')?.addEventListener('click',duplicateFlag);$('deleteFlag')?.addEventListener('click',deleteFlag);$('clearFlags')?.addEventListener('click',clearFlags);$('centerFlag')?.addEventListener('click',centerFlag);
$('flagSelect')?.addEventListener('change',e=>select(e.target.value));$('flagType')?.addEventListener('change',e=>{const f=selectedFlag();if(!f)return;f.kind=e.target.value==='image'?'image':'triangle';save();render()});$('flagSize')?.addEventListener('input',e=>setSize(e.target.value));$('flagSizeRange')?.addEventListener('input',e=>setSize(e.target.value));$('flagPoleHeight')?.addEventListener('input',e=>setPoleHeight(e.target.value));$('flagPoleHeightRange')?.addEventListener('input',e=>setPoleHeight(e.target.value));$('flagColor')?.addEventListener('input',e=>{const f=selectedFlag();if(!f)return;f.flagColor=e.target.value;save();render()});$('flagPoleColor')?.addEventListener('input',e=>{const f=selectedFlag();if(!f)return;f.poleColor=e.target.value;save();render()});$('flagDirection')?.addEventListener('change',e=>{const f=selectedFlag();if(!f)return;f.direction=e.target.value==='left'?'left':'right';save();render()});$('flagX')?.addEventListener('input',e=>setPos('x',e.target.value));$('flagY')?.addEventListener('input',e=>setPos('y',e.target.value));$('showFlags')?.addEventListener('change',e=>{state.show=e.target.checked;save();render()});$('dragFlags')?.addEventListener('change',e=>{state.dragEnabled=e.target.checked;save();render()});
$('flagImageW')?.addEventListener('input',e=>setImageDimension('w',e.target.value));$('flagImageWRange')?.addEventListener('input',e=>setImageDimension('w',e.target.value));$('flagImageH')?.addEventListener('input',e=>setImageDimension('h',e.target.value));$('flagImageHRange')?.addEventListener('input',e=>setImageDimension('h',e.target.value));$('flagLockRatio')?.addEventListener('change',e=>{const f=selectedFlag();if(!f)return;f.lockRatio=e.target.checked;if(f.lockRatio){f.imageRatio=Number(f.imageRatio)||f.imageW/f.imageH;f.imageH=clamp(f.imageW/f.imageRatio,20,280)}save();render()});$('restoreFlagImageRatio')?.addEventListener('click',restoreImageRatio);$('flagImageFit')?.addEventListener('change',e=>{const f=selectedFlag();if(!f)return;f.imageFit=e.target.value==='cover'?'cover':'contain';save();render()});$('flagBorderColor')?.addEventListener('input',e=>{const f=selectedFlag();if(!f)return;f.borderColor=e.target.value;save();render()});$('flagBorderWidth')?.addEventListener('input',e=>{const f=selectedFlag();if(!f)return;f.borderWidth=clamp(Number(e.target.value)||0,0,8);save();render()});$('flagRadius')?.addEventListener('input',e=>{const f=selectedFlag();if(!f)return;f.radius=clamp(Number(e.target.value)||0,0,30);save();render()});
$('applyFlagImageUrl')?.addEventListener('click',useImageUrl);$('chooseFlagImageFile')?.addEventListener('click',()=>$('flagImageFile')?.click());$('flagImageFile')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)chooseLocalFile(file);e.target.value=''});$('clearFlagImage')?.addEventListener('click',clearFlagImage);
svg.addEventListener('pointermove',moveDrag);svg.addEventListener('pointerup',endDrag);svg.addEventListener('pointercancel',endDrag);window.addEventListener('pagehide',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')save(true)});
if(state.flags.length)state.selected=state.flags[0].id;render();save(false);
window.__VN_FLAGS={add:addTriangleFlag,addImage:addImageFlag,render,save,getAll:()=>JSON.parse(JSON.stringify(state.flags))};
})();
